---
- name: Upgrade System
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Create k0s Directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - "{{ k0s_config_dir }}"
    - "{{ k0s_data_dir }}"
    - "{{ k0s_libexec_dir }}"

- name: Install apt packages
  apt:
    update_cache: yes
    name: jq
    state: present

# TODO: LIMIT TO CONTROLLER NODES
- name: Write the k0s config file
  template:
    src: k0s.yaml.j2
    dest: "{{ k0s_config_dir }}/k0s.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
